on:
  push:
    branch:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/timowey/SchoolBot
            if [ ! -d ".git" ]; then
              git clone https://github.com/t1mowey/SchoolBot.git .
            else
              git pull
            fi
            sudo /bin/systemctl restart schoolbot